name: video-scanner

services:
  mysql:
    image: mysql:latest
    container_name: $MYSQL_HOST
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./healthcheck.sh:/healthcheck.sh
      - mysql_data:/var/lib/mysql
    networks:
      - application
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  fastapi-auth:
    build: ./authentication-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - application

volumes:
  mysql_data:


networks:
  application:
    driver: bridge